; Listing generated by Microsoft (R) Optimizing Compiler Version 19.15.26726.0 

	TITLE	E:\coding\CPP_29Aug2018\CPP_29Aug2018\Day2\Day2\functionTemplate.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

msvcjmc	SEGMENT
__70B7E941_functiontemplate.cpp DB 01H
msvcjmc	ENDS
PUBLIC	_main
PUBLIC	??$GETMAX@HH@@YAHHH@Z				; GETMAX<int,int>
PUBLIC	??$GETMAX@H@@YAHHH@Z				; GETMAX<int>
EXTRN	@__CheckForDebuggerJustMyCode@4:PROC
EXTRN	__RTC_CheckEsp:PROC
EXTRN	__RTC_InitBase:PROC
EXTRN	__RTC_Shutdown:PROC
;	COMDAT rtc$TMZ
rtc$TMZ	SEGMENT
__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
rtc$IMZ	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ??$GETMAX@H@@YAHHH@Z
_TEXT	SEGMENT
tv65 = -196						; size = 4
_x$ = 8							; size = 4
_y$ = 12						; size = 4
??$GETMAX@H@@YAHHH@Z PROC				; GETMAX<int>, COMDAT
; File e:\coding\cpp_29aug2018\cpp_29aug2018\day2\day2\functiontemplate.cpp
; Line 3
	push	ebp
	mov	ebp, esp
	sub	esp, 196				; 000000c4H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-196]
	mov	ecx, 49					; 00000031H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	ecx, OFFSET __70B7E941_functiontemplate.cpp
	call	@__CheckForDebuggerJustMyCode@4
; Line 4
	mov	eax, DWORD PTR _x$[ebp]
	cmp	eax, DWORD PTR _y$[ebp]
	jle	SHORT $LN3@GETMAX
	mov	ecx, DWORD PTR _x$[ebp]
	mov	DWORD PTR tv65[ebp], ecx
	jmp	SHORT $LN4@GETMAX
$LN3@GETMAX:
	mov	edx, DWORD PTR _y$[ebp]
	mov	DWORD PTR tv65[ebp], edx
$LN4@GETMAX:
	mov	eax, DWORD PTR tv65[ebp]
; Line 5
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 196				; 000000c4H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
??$GETMAX@H@@YAHHH@Z ENDP				; GETMAX<int>
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ??$GETMAX@HH@@YAHHH@Z
_TEXT	SEGMENT
tv65 = -196						; size = 4
_x$ = 8							; size = 4
_y$ = 12						; size = 4
??$GETMAX@HH@@YAHHH@Z PROC				; GETMAX<int,int>, COMDAT
; File e:\coding\cpp_29aug2018\cpp_29aug2018\day2\day2\functiontemplate.cpp
; Line 16
	push	ebp
	mov	ebp, esp
	sub	esp, 196				; 000000c4H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-196]
	mov	ecx, 49					; 00000031H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	ecx, OFFSET __70B7E941_functiontemplate.cpp
	call	@__CheckForDebuggerJustMyCode@4
; Line 17
	mov	eax, DWORD PTR _x$[ebp]
	cmp	eax, DWORD PTR _y$[ebp]
	jle	SHORT $LN3@GETMAX
	mov	ecx, DWORD PTR _x$[ebp]
	mov	DWORD PTR tv65[ebp], ecx
	jmp	SHORT $LN4@GETMAX
$LN3@GETMAX:
	mov	edx, DWORD PTR _y$[ebp]
	mov	DWORD PTR tv65[ebp], edx
$LN4@GETMAX:
	mov	eax, DWORD PTR tv65[ebp]
; Line 18
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 196				; 000000c4H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
??$GETMAX@HH@@YAHHH@Z ENDP				; GETMAX<int,int>
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT _main
_TEXT	SEGMENT
_main	PROC						; COMDAT
; File e:\coding\cpp_29aug2018\cpp_29aug2018\day2\day2\functiontemplate.cpp
; Line 24
	push	ebp
	mov	ebp, esp
	sub	esp, 192				; 000000c0H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-192]
	mov	ecx, 48					; 00000030H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	ecx, OFFSET __70B7E941_functiontemplate.cpp
	call	@__CheckForDebuggerJustMyCode@4
; Line 27
	push	12					; 0000000cH
	push	10					; 0000000aH
	call	??$GETMAX@HH@@YAHHH@Z			; GETMAX<int,int>
	add	esp, 8
; Line 28
	push	2
	push	1
	call	??$GETMAX@H@@YAHHH@Z			; GETMAX<int>
	add	esp, 8
; Line 29
	xor	eax, eax
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 192				; 000000c0H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
