; Listing generated by Microsoft (R) Optimizing Compiler Version 17.00.50727.1 

	TITLE	D:\Workspace\CDAC\CPP_ElectronicCity\Day1\Day1\namingConvension2.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

PUBLIC	?fun@@YAXXZ					; fun
PUBLIC	?fun@@YAXH@Z					; fun
PUBLIC	_main
EXTRN	__RTC_CheckEsp:PROC
EXTRN	__RTC_InitBase:PROC
EXTRN	__RTC_Shutdown:PROC
;	COMDAT rtc$TMZ
rtc$TMZ	SEGMENT
__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
rtc$IMZ	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT _main
_TEXT	SEGMENT
_main	PROC						; COMDAT
; File d:\workspace\cdac\cpp_electroniccity\day1\day1\namingconvension2.cpp
; Line 15
	push	ebp
	mov	ebp, esp
	sub	esp, 192				; 000000c0H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-192]
	mov	ecx, 48					; 00000030H
	mov	eax, -858993460				; ccccccccH
	rep stosd
; Line 16
	call	?fun@@YAXXZ				; fun
; Line 17
	push	10					; 0000000aH
	call	?fun@@YAXH@Z				; fun
	add	esp, 4
; Line 18
	xor	eax, eax
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 192				; 000000c0H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ?fun@@YAXH@Z
_TEXT	SEGMENT
_arg$ = 8						; size = 4
?fun@@YAXH@Z PROC					; fun, COMDAT
; File d:\workspace\cdac\cpp_electroniccity\day1\day1\namingconvension2.cpp
; Line 13
	push	ebp
	mov	ebp, esp
	sub	esp, 192				; 000000c0H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-192]
	mov	ecx, 48					; 00000030H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
?fun@@YAXH@Z ENDP					; fun
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ?fun@@YAXXZ
_TEXT	SEGMENT
?fun@@YAXXZ PROC					; fun, COMDAT
; File d:\workspace\cdac\cpp_electroniccity\day1\day1\namingconvension2.cpp
; Line 7
	push	ebp
	mov	ebp, esp
	sub	esp, 192				; 000000c0H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-192]
	mov	ecx, 48					; 00000030H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
?fun@@YAXXZ ENDP					; fun
_TEXT	ENDS
END
